-- DROP VIEW "Rpt"."VwCommunityLeadMgmt";

CREATE OR REPLACE VIEW "Rpt"."VwCommunityLeadMgmt"
    AS (
        SELECT dd."FullDate"
            , dd."Date"
            , dd."DayName"
            , dd."DayOfYear"
            , dd."WeekOfYear"
            , dd."WeekBeginDate"
            , dd."WeekEndDate"
            , dd."MonthBeginDate"
            , dd."MonthEndDate"
            , dd."MonthName"
            , dd."MonthOfYear"
            , dd."QuarterBeginDate"
            , dd."QuarterEndDate"
            , dd."QuarterOfYear"
            , dd."FiscalQuarter"
            , dd."Year"
            , dd."YearBeginDate"
            , dd."YearEndDate"
            , dc."CommunityName"
            , dc."CommunityGroupName"
            , dc."PropertyType"
            , dc."CGCellId"
            , dc."CGGroupId"
            , dc."OwnershipEntityName"
            , dc."EquityPartnerName"
            , dc."MgmtOpCoName"
            , NULLIF(SUM(dlg."LeadCnt"), 0) AS "GoalLeadCnt"
            , dfp."FloorplanName"
            , dfp."UnitTypeName"
            , dfp."BedroomCnt"
            , dfp."BathroomCnt"
            , dpu."UnitNbr"
            , dpu."SqFt" AS "UnitSqFt"
            , dbs."BedSpaceNbr"
            , NULLIF(SUM(dbs."MktRentUSD"), 0) AS "MktRentUSD"
            , SUM(fct."NewLeadCnt") AS "NewLeadCnt"
            , SUM(fct."InitialContactEmailCnt") AS "InitialContactEmailCnt"
            , SUM(fct."InitialContactPhoneCallCnt") AS "InitialContactPhoneCallCnt"
            , SUM(fct. "InitialContactOnlineCnt") AS "InitialContactOnlineCnt"
            , SUM(fct."InitialContactChatMsgCnt") AS "InitialContactChatMsgCnt"
            , SUM(fct."InitialContactTextMsgCnt") AS "InitialContactTextMsgCnt"
            , SUM(fct."ReferredLeadInitialContactCnt") AS "ReferredLeadInitialContactCnt"
            , SUM(fct."InitialContactOnsiteTourCnt") AS "InitialContactOnsiteTourCnt"
            , SUM(fct."InitialContactOffsiteCnt") AS "InitialContactOffsiteCnt"
            , SUM(fct."InitialContactOtherCnt") AS "InitialContactOtherCnt"
            , SUM(fct."TotalLeadContactEmailCnt") AS "TotalLeadContactEmailCnt"
            , SUM(fct."TotalLeadContactPhoneCallCnt") AS "TotalLeadContactPhoneCallCnt"
            , SUM(fct."TotalLeadContactOnlineCnt") AS "TotalLeadContactOnlineCnt"
            , SUM(fct."TotalLeadContactChatMsgCnt") AS "TotalLeadContactChatMsgCnt"
            , SUM(fct."TotalLeadContactTextMsgCnt") AS "TotalLeadContactTextMsgCnt"
            , SUM(fct."OnsiteVisitCnt") AS "OnsiteVisitCnt"
            , SUM(fct."PropertyTourCnt") AS "PropertyTourCnt"
            , SUM(fct."PropertyUnitTourCnt") AS "PropertyUnitTourCnt"
            , SUM(fct."SelfGuidedTourCnt") AS "SelfGuidedTourCnt"
            , SUM(fct."VirtualTourCnt") AS "VirtualTourCnt"
            , SUM(fct."DistinctTourCnt") AS "DistinctTourCnt"
            , SUM(fct."LeadCancelledCnt") AS "LeadCancelledCnt"
            , SUM(fct."AppCompletedCnt") AS "AppCompletedCnt"
            , SUM(fct."CompletedAppCancelledCnt") AS "CompletedAppCancelledCnt"
            , SUM(fct."AppDeniedCnt") AS "AppDeniedCnt"
            , SUM(fct."AppApprovedCnt") AS "AppApprovedCnt"
            , SUM(fct."ApprovedAppCancelledCnt") AS "ApprovedAppCancelledCnt"
            , SUM(fct."LeaseCompletedCnt") AS "LeaseCompletedCnt"
            , SUM(fct."CompletedLeaseCancelledCnt") AS "CompletedLeaseCancelledCnt"
            , SUM(fct."LeaseApprovedCnt") AS "LeaseApprovedCnt"
        FROM "DDM"."FctCommunityLeadMgmtPSnap" fct 
            INNER JOIN "DDM"."DimDate" dd 
                ON(fct."DateIKey" = dd."DateIKey")
            INNER JOIN "DDM"."DimCommunity" dc 
                ON(fct."CommunitySKey" = dc."CommunitySKey")
            INNER JOIN "DDM"."DimFloorplan" dfp 
                ON(fct."FloorplanSKey" = dfp."FloorplanSKey")
            INNER JOIN "DDM"."DimPropertyUnit" dpu 
                ON(fct."PropertyUnitSKey" = dpu."PropertyUnitSKey")
            INNER JOIN "DDM"."DimBedSpace" dbs 
                ON(fct."BedSpaceSKey" = dbs."BedSpaceSKey")
            INNER JOIN "DDM"."DimLeaseGoal" dlg 
                ON(fct."LeaseGoalSKey" = dlg."LeaseGoalSKey")
        GROUP BY dd."FullDate"
            , dd."Date"
            , dd."DayName"
            , dd."DayOfYear"
            , dd."WeekOfYear"
            , dd."WeekBeginDate"
            , dd."WeekEndDate"
            , dd."MonthBeginDate"
            , dd."MonthEndDate"
            , dd."MonthName"
            , dd."MonthOfYear"
            , dd."QuarterBeginDate"
            , dd."QuarterEndDate"
            , dd."QuarterOfYear"
            , dd."FiscalQuarter"
            , dd."Year"
            , dd."YearBeginDate"
            , dd."YearEndDate"
            , dc."CommunityName"
            , dc."CommunityGroupName"
            , dc."PropertyType"
            , dc."CGCellId"
            , dc."CGGroupId"
            , dc."OwnershipEntityName"
            , dc."EquityPartnerName"
            , dc."MgmtOpCoName"
            , dfp."FloorplanName"
            , dfp."UnitTypeName"
            , dfp."BedroomCnt"
            , dfp."BathroomCnt"
            , dpu."UnitNbr"
            , dpu."SqFt"
            , dbs."BedSpaceNbr"
            , dlg."LeaseCnt"
            , dlg."CumulativeLeaseCnt"
            , dlg."CumulativeLeasePct"
        ORDER BY dd."Date"
            , dc."CommunityName"
            , dfp."FloorplanName"
            , dpu."UnitNbr"
            , dbs."BedSpaceNbr"
    );

ALTER VIEW "Rpt"."VwCommunityLeadMgmt"
    OWNER TO "Deployment";